url: https://ARMmbed.github.io
baseurl: /DAPLink/

# Site settings
title: DAPLink
email: support@mbed.com
description: "mbed DAPLink interface firmware."

# Build settings
markdown: kramdown
permalink: pretty
exclude: [vendor]

exclude:
  - tools/*
