---
website: http://os.mbed.com/platforms
fw_version: '0253'
image_format: .bin
instructions:
  default:
    windows: |-
      1. Download the firmware file.
      2. While holding down the boards reset button, connect the boards USB debug port to the computer. It should enumerate and mount as `BOOTLOADER` or `MAINTENANCE`. For boards that enumerate as `BOOTLOADER` [see our blog to determine if an update for the DAPLink bootloader is available.](https://os.mbed.com/blog/entry/DAPLink-bootloader-update/)
      3. Drag-and-drop the firmware file onto the mounted drive.
      4. Wait for the file copy operation to complete.
      5. Power cycle the board. It will now enumerate and mount as `DAPLINK` or the name of the board.
    osx: |-
      1. Download the firmware file.
      2. While holding down the boards reset button, connect the boards USB debug port to the computer. It should enumerate as `BOOTLOADER` or `MAINTENANCE`. For boards that enumerate as `BOOTLOADER` [see our blog to determine if an update for the DAPLink bootloader is available.](https://os.mbed.com/blog/entry/DAPLink-bootloader-update/)
      3. In a terminal execute
         - `sudo mount -u -w -o sync /Volumes/MAINTENANCE ; cp -X <path to firmware file> /Volumes/MAINTENANCE/`
         - Note: If your drive does not mount as `MAINTENANCE` make sure to change this to match the name of the mounted disk attached to your system.
      4. Wait for the file copy operation to complete.
      5. Power cycle the board. It will now enumerate and mount as `DAPLINK` or the name of the board.
    linux: |-
      1. Download the firmware file.
      2. While holding down the boards reset button, connect the boards USB debug port to the computer. It should enumerate as `BOOTLOADER` or `MAINTENANCE`. For boards that enumerate as `BOOTLOADER` [see our blog to determine if an update for the DAPLink bootloader is available.](https://os.mbed.com/blog/entry/DAPLink-bootloader-update/)
      3. In a terminal execute
         - `cp <path to firmware file> <MAINTENANCE> && sync`
         - Note: make sure to change `MAINTENANCE` to the name of the mount point of the drive on your system.
      4. Power cycle the board. It will now enumerate and mount as `DAPLINK` or the name of the board.
  lpc11u35:
    linux: |-
      1. Download the firmware file.
      2. While holding down the boards reset button, connect the boards USB debug port to the computer. It should enumerate and mount as `CRP DISABLD`
      3. Delete the file named `firmware.bin`
      4. In a terminal execute
         - `cp <path to firmware file> <CRP DISABLD> && sync`
         - Note: make sure to change `CRP DISABLD` to the name of the mount point on your system.
      5. Power cycle the board. It will now enumerate and mount as `DAPLINK` or the name of the board.
    osx: |-
      1. Download the firmware file.
      2. While holding down the boards reset button, connect the boards USB debug port to the computer. It should enumerate and mount as `CRP DISABLD`
      3. Delete the file named `firmware.bin`
      4. In a terminal execute
         - `sudo mount -u -w -o sync /Volumes/CRP\ DISABLD ; rm /Volumes/CRP\ DISABLD/firmware.bin && cp -X <path to firmware file> /Volumes/CRP\ DISABLD/`
      5. Wait for the file copy operation to complete.
      6. Power cycle the board. It will now enumerate and mount as `DAPLINK` or the name of the board.
    windows: |-
      1. Download the firmware file.
      2. While holding down the boards reset button, connect the boards USB debug port to the computer. It should enumerate and mount as `CRP DISABLD`
      3. Delete the file named `firmware.bin`, then drag and drop or copy the new bin file
      4. Wait for the file copy operation to complete.
      5. Power cycle the board. It will now enumerate and mount as `DAPLINK` or the name of the board.
